runtime: python311  
entrypoint: gunicorn -b :$PORT app:app
service: chatbot-be
instance_class: F2  


env_variables:
  GOOGLE_CLOUD_PROJECT: 
  BUCKET_NAME: 
  GOOGLE_APPLICATION_CREDENTIALS: 

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
