runtime: python310

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_CLOUD_PROJECT: 
  BUCKET_NAME: 
  GOOGLE_APPLICATION_CREDENTIALS: ""

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

instance_class: 
service: 

